// <auto-generated />
using System;
using EM.Maman.Models.LocalDbModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EM.Maman.Models.Migrations
{
    [DbContext(typeof(LocalMamanDBContext))]
    [Migration("20250513172800_IncreaseTaskNameLength")]
    partial class IncreaseTaskNameLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // The rest of the model definition is omitted for brevity
            // This is a partial class that only needs to define the migration attributes
#pragma warning restore 612, 618
        }
    }
}
