// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Maman.Models.LocalDbModels;

public partial class Cell
{
    public long Id { get; set; }

    public string DisplayName { get; set; }

    public int? Position { get; set; }

    public int? Level { get; set; }

    public bool? IsSecuredStorage { get; set; }

    public int? HeightLevel { get; set; }

    public int? Order { get; set; }

    public int? RefrigerationTypeId { get; set; }

    public bool? IsBlocked { get; set; }

    public int? Side { get; set; }

    public int? IsBlockedReasonId { get; set; }

    public DateTime? LastModified { get; set; }

    public int? Depth { get; set; }

    public virtual Level HeightLevelNavigation { get; set; }
}