// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Maman.Models.LocalDbModels;

public partial class Configuration
{
    public int Id { get; set; }

    public DateTime InitializedAt { get; set; }

    public string InitializedByEmployeeId { get; set; }

    public string WorkstationType { get; set; }
}