// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Maman.Models.LocalDbModels;

public partial class Finger
{
    public long Id { get; set; }

    public int? Position { get; set; }

    public string Description { get; set; }

    public string DisplayName { get; set; }

    public string DisplayColor { get; set; }

    public int? Side { get; set; }

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}