// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Maman.Models.LocalDbModels;

public partial class Level
{
    public long Id { get; set; }

    public string DisplayName { get; set; }

    public int Number { get; set; }

    public virtual ICollection<Cell> Cells { get; set; } = new List<Cell>();
}