// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EM.Maman.Models.LocalDbModels;

public partial class LocalMamanDBContext : DbContext
{
    public LocalMamanDBContext()
    {
    }

    public LocalMamanDBContext(DbContextOptions<LocalMamanDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Finger> Fingers { get; set; }

    public virtual DbSet<Location> Locations { get; set; }

    public virtual DbSet<LocationType> LocationTypes { get; set; }

    public virtual DbSet<Pallet> Pallets { get; set; }

    public virtual DbSet<PalletMovementLog> PalletMovementLogs { get; set; }

    public virtual DbSet<RefrigerationType> RefrigerationTypes { get; set; }

    public virtual DbSet<StorageType> StorageTypes { get; set; }

    public virtual DbSet<Task> Tasks { get; set; }

    public virtual DbSet<TaskDetail> TaskDetails { get; set; }

    public virtual DbSet<TaskLog> TaskLogs { get; set; }

    public virtual DbSet<TraceLog> TraceLogs { get; set; }

    public virtual DbSet<Trolley> Trolleys { get; set; }

    public virtual DbSet<TrolleyLoadingLocation> TrolleyLoadingLocations { get; set; }

    public virtual DbSet<TrolleyMovementLog> TrolleyMovementLogs { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=LocalMamanDB;Integrated Security=True;Pooling=False;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Finger>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07767BB490");

            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.DisplayColor).HasMaxLength(50);
            entity.Property(e => e.DisplayName).HasMaxLength(50);
        });

        modelBuilder.Entity<Location>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Location__3214EC0732F7F4E1");

            entity.Property(e => e.Capacity).HasColumnName("capacity");
            entity.Property(e => e.DisplayName).HasMaxLength(50);
            entity.Property(e => e.HeightLevel).HasDefaultValueSql("((0))");
            entity.Property(e => e.IsActive).HasDefaultValueSql("((1))");
        });

        modelBuilder.Entity<LocationType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Location__3214EC07240A40C1");

            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.DisplayName).HasMaxLength(50);
            entity.Property(e => e.Displaycolor).HasMaxLength(50);
        });

        modelBuilder.Entity<Pallet>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Pallets__3214EC075B4002B5");

            entity.Property(e => e.CheckedOutDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.DisplayName).HasMaxLength(200);
            entity.Property(e => e.IsCheckedOut).HasDefaultValueSql("((0))");
            entity.Property(e => e.LastModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.MamanCode).HasMaxLength(50);
            entity.Property(e => e.ReceivedDate).HasColumnType("datetime");
            entity.Property(e => e.StorageCode).HasMaxLength(50);
        });

        modelBuilder.Entity<PalletMovementLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PalletMo__3214EC07502484D2");

            entity.Property(e => e.CreateDate)
                .HasColumnType("datetime")
                .HasColumnName("createDate");
            entity.Property(e => e.Description).HasMaxLength(200);
        });

        modelBuilder.Entity<RefrigerationType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07DD6A0605");

            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.DisplayColor).HasMaxLength(50);
            entity.Property(e => e.DisplayName).HasMaxLength(50);
        });

        modelBuilder.Entity<StorageType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07B2FB596A");

            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.DisplayColor).HasMaxLength(50);
            entity.Property(e => e.DisplayName).HasMaxLength(50);
        });

        modelBuilder.Entity<Task>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Tasks__3214EC0749F74CCB");

            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.DownloadDate).HasColumnType("datetime");
            entity.Property(e => e.ExecutedDate).HasColumnType("datetime");
            entity.Property(e => e.IsExecuted).HasDefaultValueSql("((0))");
            entity.Property(e => e.IsUploaded).HasDefaultValueSql("((0))");
            entity.Property(e => e.Name).HasMaxLength(50);
            entity.Property(e => e.UploadDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TaskDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TaskDeta__3214EC07CEBCA418");

            entity.Property(e => e.ExecutedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TaskLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TaskLogs__3214EC0722E0A04E");

            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(200);
        });

        modelBuilder.Entity<TraceLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TraceLog__3214EC074AE5E671");

            entity.Property(e => e.Request).HasMaxLength(200);
            entity.Property(e => e.RequestBody).HasMaxLength(200);
            entity.Property(e => e.ResponseBody).HasMaxLength(200);
            entity.Property(e => e.ResponseCode).HasMaxLength(50);
            entity.Property(e => e.Url).HasMaxLength(200);
        });

        modelBuilder.Entity<Trolley>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC0737E90462");

            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.DisplayName).HasMaxLength(50);
        });

        modelBuilder.Entity<TrolleyLoadingLocation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07785E6850");

            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.DisplayColor).HasMaxLength(50);
            entity.Property(e => e.DisplayName).HasMaxLength(50);
            entity.Property(e => e.Side).HasMaxLength(50);
        });

        modelBuilder.Entity<TrolleyMovementLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TrolleyM__3214EC077DBF64AA");

            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.StartDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3214EC0763E2D4F3");

            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.LastLoginDate).HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}