// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Maman.Models.LocalDbModels;

public partial class Location
{
    public long Id { get; set; }

    public string DisplayName { get; set; }

    public int? Position { get; set; }

    public int? Level { get; set; }

    public int? StorageTypeId { get; set; }

    public int? HeightLevel { get; set; }

    public int? Capacity { get; set; }

    public int? RefrigerationTypeId { get; set; }

    public bool? IsActive { get; set; }

    public int? Side { get; set; }
}