// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EM.Maman.Models.LocalDbModels;

public partial class LocalMamanDBContext : DbContext
{
    public LocalMamanDBContext(DbContextOptions<LocalMamanDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Alert> Alerts { get; set; }

    public virtual DbSet<Cell> Cells { get; set; }

    public virtual DbSet<CellType> CellTypes { get; set; }

    public virtual DbSet<Configuration> Configurations { get; set; }

    public virtual DbSet<Finger> Fingers { get; set; }

    public virtual DbSet<Level> Levels { get; set; }

    public virtual DbSet<Pallet> Pallets { get; set; }

    public virtual DbSet<PalletInCell> PalletInCells { get; set; }

    public virtual DbSet<PalletMovementLog> PalletMovementLogs { get; set; }

    public virtual DbSet<PendingOperation> PendingOperations { get; set; }

    public virtual DbSet<RefrigerationType> RefrigerationTypes { get; set; }

    public virtual DbSet<StorageType> StorageTypes { get; set; }

    public virtual DbSet<Task> Tasks { get; set; }

    public virtual DbSet<TaskDetail> TaskDetails { get; set; }

    public virtual DbSet<TaskLog> TaskLogs { get; set; }

    public virtual DbSet<TaskType> TaskTypes { get; set; }

    public virtual DbSet<TraceLog> TraceLogs { get; set; }

    public virtual DbSet<Trolley> Trolleys { get; set; }

    public virtual DbSet<TrolleyCell> TrolleyCells { get; set; }

    public virtual DbSet<TrolleyLoadingLocation> TrolleyLoadingLocations { get; set; }

    public virtual DbSet<TrolleyMovementLog> TrolleyMovementLogs { get; set; }

    public virtual DbSet<UploadTask> UploadTasks { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Alert>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07C13F34DE");

            entity.Property(e => e.Color).HasMaxLength(50);
            entity.Property(e => e.ConfirmedDate).HasColumnType("datetime");
            entity.Property(e => e.Content).HasMaxLength(200);
            entity.Property(e => e.DownloadDate).HasColumnType("datetime");
            entity.Property(e => e.Title).HasMaxLength(50);
        });

        modelBuilder.Entity<Cell>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Cells__3214EC074D1016A6");

            entity.Property(e => e.DisplayName).HasMaxLength(50);
            entity.Property(e => e.HeightLevel).HasDefaultValueSql("((0))");
            entity.Property(e => e.IsBlocked).HasDefaultValueSql("((1))");
            entity.Property(e => e.IsSecuredStorage).HasDefaultValueSql("((0))");
            entity.Property(e => e.LastModified).HasColumnType("datetime");

            entity.HasOne(d => d.HeightLevelNavigation).WithMany(p => p.Cells)
                .HasPrincipalKey(p => p.Number)
                .HasForeignKey(d => d.HeightLevel)
                .HasConstraintName("FK_Cells_Levels");
        });

        modelBuilder.Entity<CellType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CellType__3214EC07AACF101F");

            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.DisplayColor).HasMaxLength(50);
            entity.Property(e => e.DisplayName).HasMaxLength(50);
        });

        modelBuilder.Entity<Configuration>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Configur__3214EC079B1E2953");

            entity.Property(e => e.InitializedAt).HasDefaultValueSql("('0001-01-01T00:00:00.0000000')");
        });

        modelBuilder.Entity<Finger>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07767BB490");

            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.DisplayColor).HasMaxLength(50);
            entity.Property(e => e.DisplayName).HasMaxLength(50);
        });

        modelBuilder.Entity<Level>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Levels__3214EC0796D8C15E");

            entity.HasIndex(e => e.Number, "UQ_Levels_Number").IsUnique();

            entity.Property(e => e.DisplayName).HasMaxLength(50);
        });

        modelBuilder.Entity<Pallet>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Pallets__3214EC075B4002B5");

            entity.Property(e => e.AwbCode).HasMaxLength(50);
            entity.Property(e => e.CargoType).HasConversion<int>();
            entity.Property(e => e.UpdateType).HasConversion<int>();
            entity.Property(e => e.StorageType).HasConversion<int>();
            entity.Property(e => e.HeightType).HasConversion<int>();
            entity.Property(e => e.ReportType).HasConversion<int>().HasDefaultValue(Enums.ReportType.REQ);
            entity.Property(e => e.CheckedOutDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.DisplayName).HasMaxLength(200);
            entity.Property(e => e.ExportAwbAppearance).HasMaxLength(50);
            entity.Property(e => e.ExportAwbNumber).HasMaxLength(50);
            entity.Property(e => e.ExportAwbStorage).HasMaxLength(50);
            entity.Property(e => e.ExportBarcode).HasMaxLength(50);
            entity.Property(e => e.ExportSwbPrefix).HasMaxLength(50);
            entity.Property(e => e.ImportAppearance).HasMaxLength(50);
            entity.Property(e => e.ImportManifest).HasMaxLength(50);
            entity.Property(e => e.ImportUnit).HasMaxLength(50);
            entity.Property(e => e.IsCheckedOut).HasDefaultValueSql("((0))");
            entity.Property(e => e.IsSecure).HasDefaultValueSql("((0))");
            entity.Property(e => e.LastModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.ReceivedDate).HasColumnType("datetime");
            entity.Property(e => e.UldAirline).HasMaxLength(50);
            entity.Property(e => e.UldCode).HasMaxLength(50);
            entity.Property(e => e.UldNumber).HasMaxLength(50);
            entity.Property(e => e.UldType).HasMaxLength(50);
        });

        modelBuilder.Entity<PalletInCell>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PalletIn__3214EC0738C95D89");

            entity.ToTable("PalletInCell");

            entity.Property(e => e.StorageDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<PalletMovementLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PalletMo__3214EC07502484D2");

            entity.Property(e => e.CreateDate)
                .HasColumnType("datetime")
                .HasColumnName("createDate");
            entity.Property(e => e.Description).HasMaxLength(200);
        });

        modelBuilder.Entity<PendingOperation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PendingO__3214EC0756C73109");

            entity.ToTable("PendingOperation");

            entity.Property(e => e.CommandType).HasMaxLength(50);
            entity.Property(e => e.CompletedAt).HasColumnType("datetime");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.ErrorMessage).HasMaxLength(50);
            entity.Property(e => e.Parameters)
                .HasMaxLength(50)
                .HasColumnName("Parameters ");
            entity.Property(e => e.Status).HasMaxLength(50);
        });

        modelBuilder.Entity<RefrigerationType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07DD6A0605");

            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.DisplayColor).HasMaxLength(50);
            entity.Property(e => e.DisplayName).HasMaxLength(50);
        });

        modelBuilder.Entity<StorageType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07B2FB596A");

            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.DisplayColor).HasMaxLength(50);
            entity.Property(e => e.DisplayName).HasMaxLength(50);
        });

        modelBuilder.Entity<Task>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Tasks__3214EC0749F74CCB");

            entity.HasIndex(e => e.CellEndLocationId, "IX_Tasks_CellEndLocationId");

            entity.HasIndex(e => e.FingerLocationId, "IX_Tasks_FingerLocationId");

            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.DownloadDate).HasColumnType("datetime");
            entity.Property(e => e.ExecutedDate).HasColumnType("datetime");
            entity.Property(e => e.IsExecuted).HasDefaultValueSql("((0))");
            entity.Property(e => e.IsUploaded).HasDefaultValueSql("((0))");
            entity.Property(e => e.Name).HasMaxLength(50);
            entity.Property(e => e.PalletId).HasMaxLength(50);
            entity.Property(e => e.UploadDate).HasColumnType("datetime");
            entity.Property(e => e.Status).HasDefaultValue(1); // Default to Created (1)
            entity.Property(e => e.ActiveTaskStatus).HasDefaultValue(1); // Default to retrieval (1)

            entity.HasOne(d => d.CellEndLocation).WithMany(p => p.Tasks).HasForeignKey(d => d.CellEndLocationId);

            entity.HasOne(d => d.FingerLocation).WithMany(p => p.Tasks).HasForeignKey(d => d.FingerLocationId);
        });

        modelBuilder.Entity<TaskDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TaskDeta__3214EC07CEBCA418");

            entity.Property(e => e.ExecutedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TaskLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TaskLogs__3214EC0722E0A04E");

            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(200);
        });

        modelBuilder.Entity<TaskType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TaskType__3214EC077981986E");

            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.DisplayName).HasMaxLength(50);
        });

        modelBuilder.Entity<TraceLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TraceLog__3214EC074AE5E671");

            entity.Property(e => e.Request).HasMaxLength(200);
            entity.Property(e => e.RequestBody).HasMaxLength(200);
            entity.Property(e => e.ResponseBody).HasMaxLength(200);
            entity.Property(e => e.ResponseCode).HasMaxLength(50);
            entity.Property(e => e.Url).HasMaxLength(200);
        });

        modelBuilder.Entity<Trolley>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC0737E90462");

            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.DisplayName).HasMaxLength(50);
        });

        modelBuilder.Entity<TrolleyCell>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TrolleyC__3214EC07XXXXXXXX");

            entity.Property(e => e.Position).HasMaxLength(50);
            entity.Property(e => e.StorageDate).HasColumnType("datetime");

            entity.HasOne(d => d.Trolley)
                .WithMany(p => p.TrolleyCells)
                .HasForeignKey(d => d.TrolleyId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_TrolleyCells_Trolleys");

            entity.HasOne(d => d.Pallet)
                .WithMany()
                .HasForeignKey(d => d.PalletId)
                .HasConstraintName("FK_TrolleyCells_Pallets");
        });

        modelBuilder.Entity<TrolleyLoadingLocation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07785E6850");

            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.DisplayColor).HasMaxLength(50);
            entity.Property(e => e.DisplayName).HasMaxLength(50);
            entity.Property(e => e.Side).HasMaxLength(50);
        });

        modelBuilder.Entity<TrolleyMovementLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TrolleyM__3214EC077DBF64AA");

            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.StartDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<UploadTask>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC0781E6720C");

            entity.Property(e => e.UploadType).HasMaxLength(50);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3214EC0763E2D4F3");

            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.LastLoginDate).HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
