// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Maman.Models.LocalDbModels;

public partial class Pallet
{
    public int Id { get; set; }

    public string DisplayName { get; set; }

    public string Description { get; set; }

    public string MamanCode { get; set; }

    public string StorageCode { get; set; }

    public DateTime? ReceivedDate { get; set; }

    public DateTime? LastModifiedDate { get; set; }

    public int? RefrigerationType { get; set; }

    public int? HeightLevel { get; set; }

    public bool? IsCheckedOut { get; set; }

    public DateTime? CheckedOutDate { get; set; }

    public long? LocationId { get; set; }

    public int? StorageType { get; set; }
}