// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EM.Maman.Models.Enums;

namespace EM.Maman.Models.LocalDbModels;

public partial class Pallet
{
    public int Id { get; set; }

    public string DisplayName { get; set; }

    public string Description { get; set; }

    public string UldCode { get; set; }

    public string AwbCode { get; set; }

    public DateTime? ReceivedDate { get; set; }

    public DateTime? LastModifiedDate { get; set; }

    public int? RefrigerationType { get; set; }

    public int? HeightLevel { get; set; }

    public bool? IsCheckedOut { get; set; }

    public DateTime? CheckedOutDate { get; set; }

    public long? LocationId { get; set; }

    public bool? IsSecure { get; set; }

    public CargoType? CargoType { get; set; }

    public UpdateType? UpdateType { get; set; }

    public StorageTypeEnum? StorageType { get; set; }

    public HeightType? HeightType { get; set; }

    public int? CargoHeight { get; set; }

    public ReportType ReportType { get; set; } = ReportType.REQ;

    public string ImportManifest { get; set; }

    public string ImportUnit { get; set; }

    public string ImportAppearance { get; set; }

    public string ExportSwbPrefix { get; set; }

    public string ExportAwbNumber { get; set; }

    public string ExportAwbAppearance { get; set; }

    public string ExportAwbStorage { get; set; }

    public string ExportBarcode { get; set; }

    public string UldType { get; set; }

    public string UldNumber { get; set; }

    public string UldAirline { get; set; }
    
    // Added property to fix binding errors
    public int? CargoTypeId => (int?)CargoType;
}
