// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Maman.Models.LocalDbModels;

public partial class PalletMovementLog
{
    public long Id { get; set; }

    public long? PalletId { get; set; }

    public long? FromLocationId { get; set; }

    public long? FromLocationTypeId { get; set; }

    public long? ToLocationId { get; set; }

    public long? ToLocationTypeId { get; set; }

    public DateTime? CreateDate { get; set; }

    public string Description { get; set; }
}