// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Maman.Models.LocalDbModels;

public partial class PalletInCell
{
    public int Id { get; set; }

    public long? PalletId { get; set; }

    public long? CellId { get; set; }

    public DateTime? StorageDate { get; set; }
}