// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Maman.Models.LocalDbModels;

public partial class PendingOperation
{
    public long Id { get; set; }

    public string CommandType { get; set; }

    public string Parameters { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public string Status { get; set; }

    public string ErrorMessage { get; set; }

    public int? RetryCount { get; set; }

    public long? UserId { get; set; }
}