// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Maman.Models.LocalDbModels;

public partial class TaskLog
{
    public long Id { get; set; }

    public long? TaskId { get; set; }

    public string Description { get; set; }

    public DateTime? CreateDate { get; set; }

    public long? ReportedLocationId { get; set; }
}