// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Maman.Models.LocalDbModels;

public partial class TaskDetail
{
    public int Id { get; set; }

    public long? TaskId { get; set; }

    public long? PalletId { get; set; }

    public long? DoneLocationId { get; set; }

    public DateTime? ExecutedDate { get; set; }

    public bool? IsExecuted { get; set; }
}