// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Maman.Models.LocalDbModels;

public partial class TaskType
{
    public long Id { get; set; }

    public int? Code { get; set; }

    public string DisplayName { get; set; }

    public string Description { get; set; }
}