// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Maman.Models.LocalDbModels;

public partial class Task
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public DateTime? DownloadDate { get; set; }

    public bool? IsExecuted { get; set; }

    public DateTime? ExecutedDate { get; set; }

    public bool? IsUploaded { get; set; }

    public DateTime? UploadDate { get; set; }

    public long? TaskTypeId { get; set; }

    public long? CellEndLocationId { get; set; }

    public long? CurrentTrolleyLocationId { get; set; }

    public long? FingerLocationId { get; set; }

    public string PalletId { get; set; }

    public string Code { get; set; }
}