// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Maman.Models.LocalDbModels;

public partial class TrolleyLoadingLocation
{
    public long Id { get; set; }

    public long? TrolleyId { get; set; }

    public string DisplayName { get; set; }

    public string Description { get; set; }

    public string Side { get; set; }

    public string DisplayColor { get; set; }
}