// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Maman.Models.LocalDbModels;

/// <summary>
/// Represents a cell on a trolley that can hold a pallet
/// </summary>
public partial class TrolleyCell
{
    /// <summary>
    /// The unique identifier for the trolley cell
    /// </summary>
    public long Id { get; set; }

    /// <summary>
    /// The ID of the trolley this cell belongs to
    /// </summary>
    public long TrolleyId { get; set; }

    /// <summary>
    /// The position of this cell on the trolley (e.g., "Left" or "Right")
    /// </summary>
    public string Position { get; set; }

    /// <summary>
    /// The ID of the pallet currently in this cell, if any
    /// </summary>
    public int? PalletId { get; set; }

    /// <summary>
    /// The date and time when the pallet was placed in this cell
    /// </summary>
    public DateTime? StorageDate { get; set; }

    /// <summary>
    /// Navigation property to the trolley
    /// </summary>
    public virtual Trolley Trolley { get; set; }

    /// <summary>
    /// Navigation property to the pallet
    /// </summary>
    public virtual Pallet Pallet { get; set; }
}
