// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Maman.Models.LocalDbModels;

public partial class TrolleyMovementLog
{
    public long Id { get; set; }

    public long? FromLocationId { get; set; }

    public long? PlannedToLocationId { get; set; }

    public long? ReportedToLocationId { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public bool IsSuccessful { get; set; }

    public long? CompletedReasonId { get; set; }
}