// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EM.Maman.Models.LocalDbModels;

public partial class User
{
    public int Id { get; set; } // Local DB Primary Key

    // public string Name { get; set; } // Replaced by FirstName and LastName

    public string EmployeeCode { get; set; } // Renamed from Code, this is the EmployeeCode from login

    public DateTime? LastLoginDate { get; set; }

    public int BackendId { get; set; } // UserID from the server

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int RoleID { get; set; } // RoleID from the server

    public string Token { get; set; } // JWT received from the server
}
